start

repeat

    if (フルデータ格納済みか？) then (yes)
    else (no)
      :フルデータ取得<
      :格納]
    endif

    :データロード]

    if (生データ格納済みか？) then (yes)
    else (no)
    :生データ取得<
    :格納]
    endif

    if (期限切れか？) then (yes)
      :最小データ取得<
      if (INBOXにあるか？) then (yes)
        if (スターがついているか？) then (yes)
        else (no)
        :ごみ箱に移動>
        endif
        else (no)
      endif
    else (no)
    endif
repeat while (まだあるか？)

stop
